"""add memories table

Revision ID: bfb1033cc32f
Revises: 77a7f0c87c69
Create Date: 2026-04-25 21:35:38.631483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfb1033cc32f'
down_revision: Union[str, None] = '77a7f0c87c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('namespace', sa.String(length=50), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('source_stage', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('corroborations', sa.Integer(), nullable=False),
    sa.Column('contradictions', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_confidence', 'memories', ['confidence'], unique=False)
    op.create_index('ix_memories_namespace', 'memories', ['namespace'], unique=False)
    op.create_index('ix_memories_ns_confidence', 'memories', ['namespace', 'confidence'], unique=False)
    op.create_index('ix_memories_run_id', 'memories', ['run_id'], unique=False)
    op.create_index('ix_memories_source_stage', 'memories', ['source_stage'], unique=False)
    op.create_index('ix_memories_valid_to', 'memories', ['valid_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memories_valid_to', table_name='memories')
    op.drop_index('ix_memories_source_stage', table_name='memories')
    op.drop_index('ix_memories_run_id', table_name='memories')
    op.drop_index('ix_memories_ns_confidence', table_name='memories')
    op.drop_index('ix_memories_namespace', table_name='memories')
    op.drop_index('ix_memories_confidence', table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
