"""add runs.final_stage and runs.memory_results

Revision ID: c7a95bfd1552
Revises: bfb1033cc32f
Create Date: 2026-04-25 22:10:50.112708
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7a95bfd1552'
down_revision: Union[str, None] = 'bfb1033cc32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('final_stage', sa.String(length=50), nullable=True))
    op.add_column('runs', sa.Column('memory_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'memory_results')
    op.drop_column('runs', 'final_stage')
    # ### end Alembic commands ###
