"""initial schema

Revision ID: e8157a385508
Revises:
Create Date: 2026-04-11 18:50:32.221023
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e8157a385508"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "models_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("s3_events_key", sa.String(length=500), nullable=True),
        sa.Column("s3_replay_key", sa.String(length=500), nullable=True),
        sa.Column("s3_tracker_key", sa.String(length=500), nullable=True),
        sa.Column("s3_analyst_key", sa.String(length=500), nullable=True),
        sa.Column("s3_pdf_key", sa.String(length=500), nullable=True),
        sa.Column("s3_tex_key", sa.String(length=500), nullable=True),
        sa.Column("s3_charts_prefix", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("problem_description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("s3_report_key", sa.String(length=500), nullable=True),
        sa.Column("s3_prefix", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("experiment_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_table(
        "models",
        sa.Column("formulation_id", sa.String(length=255), nullable=False),
        sa.Column("class_name", sa.String(length=255), nullable=False),
        sa.Column("paradigm", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("s3_model_key", sa.String(length=500), nullable=False),
        sa.Column("s3_test_key", sa.String(length=500), nullable=True),
        sa.Column(
            "registered_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("formulation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("models")
    op.drop_table("artifacts")
    op.drop_table("runs")
    op.drop_table("experiments")
    # ### end Alembic commands ###
